# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules

stages:
  - test

unit_test:
  stage: test
  tags:
   - node
  before_script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build
  script:
   - yarn
   - yarn test:unit:coverage
  after_script:
   - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"

build:
  stage: test
  tags:
   - node
  script:
  - yarn
  - yarn build --publish=never
