language: node_js

env:
  global:
    - IS_DOCKER=false

matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      language: node_js
      node_js: "10"
      env: ELECTRON_CACHE=$HOME/.cache/electron ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder DO_COVERAGE=false

    - os: linux
      language: node_js
      node_js: "10"
      env: DO_COVERAGE=true

    - os: linux
      services: docker
      language: generic
      env: IS_DOCKER=true DO_COVERAGE=false
  allow_failures:
    - env: IS_DOCKER=true

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

notifications:
  email: false

before_script:
  - if [ "$DO_COVERAGE" == "true" ]; then
      ./ci/setup-coverage.sh
    fi

script:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      if [ "$IS_DOCKER" == "true" ]; then
        ./ci/build-docker.sh
      else
        ./ci/build-unix.sh
      fi
    else
      ./ci/build-mac.sh
    fi

after_script:
  - |
    if [ "$DO_COVERAGE" == "true" ]; then
      ./cc-test-reporter after-build
    fi

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine
