language: node_js

matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      language: node_js
      node_js: "10"
      env: ELECTRON_CACHE=$HOME/.cache/electron ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

    - os: linux
      language: node_js
      node_js: "10"

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

notifications:
  email: false

before_script:
  - yarn
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter; fi
  - if [ "$TRAVIS_OS_NAME" != "linux" ]; then curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter; fi
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - yarn test:unit
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then yarn build --publish=onTag --linux; fi
  - if [ "$TRAVIS_OS_NAME" != "linux" ]; then yarn build --publish=onTag --mac; fi

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine
